language: ruby

rvm:
  - 2.5.1

cache:
  bundler: true
  yarn: true

services:
  - postgresql

before_install:
  - gem install bundler
  - npm install -g yarn

before_script:
  - bundle exec rails db:setup
  - yarn

script:
  - bundle exec bundle audit --update
  - bundle exec rubocop
  - bundle exec reek
  - bundle exec rspec --format progress --no-profile

notifications:
  email: false
